### ISSUE TITLE
Strapi Media Library settings

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#308]
- Milliseid failiformaate saame üles laadida, et need oleks lehel kasutatavad, piltidena? tiff, png, jpg, bmp, webp (ei toimi safaris)
- 
- Kas saame failiformaate muuta? E kas Strapis Media library saab teha TIFFist JPG näiteks?

- Milliseid parameetreid saame muuta piltidel:
-- Pixlimõõt küljesuhet e proportsiooni säilitades?
-- Crop, 500 x 500 pixlit näiteks?
-- Pildi kvaliteet e pakkimise aste?
-- Pakkimise algoritm?

- Mitu erinevat versiooni yhest üles laeavast pildist saame teha? HD, SD, Portait, Ruut, thumbnail jne?

- Millise suurusega faile saab üles laadida?
-- Kas faili suurus on puhtalt meie määrata vüi on seal ka Strapi limiit ees? Seda nii piltide puhul, mia tahame ise näidata lehel, kui ka ataachmendiks mõeldud failide puhul (joonis, suur pilt jne)

e iga pildi kohta:
- faili formaat (.jog, .png, jne)
- faili pakkealgoritm
- pakkeaste
- versioonide kirjeldused:
-- crop / resize?
-- pixlimõõt laius / kõrgus
-- failinime suffiks

**Comment by mitselek** [comment]
https://forum.strapi.io/t/how-to-resize-uploaded-images-to-custom-sizes/4064

**Comment by mitselek** [comment]
Saali pilte juhitakse siin: https://github.com/i-b-c/KGS-Strapi/tree/main/extensions/upload

**Comment by LiisKasper** [comment]
Pildi suurus ja selle muutmine: https://strapi.io/documentation/developer-docs/latest/development/plugins/upload.html#configuration
![Screenshot from 2021-11-23 21-45-05](https://user-images.githubusercontent.com/68702810/143094298-46745715-3098-4a5d-93cb-4f14a8952e56.png)

**Comment by mitselek** [comment]
See vajab nüüd töötavaid koodijuppe.

Use case #2

Use case 1:

Kasutaja laeb üles pildi

Soovime, et vastavalt mudelile renderdataks sellest vajalik arv eri mõõdus pilte.
Konfiguratsioon umbes selline:

``` yaml
film:
  versions:
    - sx: HDTV
      w: 1920
      h: 1080
      chain:
        - scale_to_enclose
        - crop_center
    - sx: thumb
      w: 300
      h: 300
      chain:
        - scale_to_enclose
        - crop_center
        - effect_BW
        - EXIF:
            - custom_label1: custom_text
            - custom_label2: custom_text
screening:
  chain:
    - scale_to_fit
    - crop_center
  versions:
    - sx: HDTV
      w: 1920
      h: 1080
    - sx: TV
      w: 800
      h: 600
      chain: effect_old_tv

```
