### ISSUE TITLE
Strapist tabelisse filmide ja kassettide info koos F_1 _med_16_9 pildiga

### ISSUE THREAD

**Issue by jaanleppik** [poff-bnff/web2021#595]
@LiisKasper palun tee tabelisse väljavõte Strapist, kus oleks

- kasseti eestikeelne pealkiri
- kasseti eestikeelne slug
- kasseti votemo slug: chat_w_name
- kasseti F_1 med_16_9 pildi versiooni URL
- filmi eestikeelne pealkiri
- filmi eestikeeln eslug
- filmi votemo slug: chat_w_name
- filmi F_1 med_16_9 pildi versiooni URL

**Comment by LiisKasper** [comment]
Nagu aru saan siis tahad tabelit kahe sakiga films ja cassettes.
Ühel siis kõik filmid ja teisel kassetid nimetatud infoga.

Kas seda päringut peab saama teha korduvalt või piisab kui teen tabeli valmis ja tehtud?


> tabeli mõte on selles, et me saaksime Votemo süsteemi kasutuse sisendi

Mida selle all silmas peab? Läbi selle tabeli peab midagi veel toimuma?

**Comment by jaanleppik** [comment]
Ideaalis tahaks et film ja kassett oleks ühel sheedil, või siis vähemalt seosed nende vahel oleks olemas. mis cassette'i iga film kuulub
Päringut peaks saama välja kutsuda, 
Päring peaks töötama festival editioni ID'de loetlu alusel

Edasi siis hakkan ise valemeid kirjutama, et meie tabeli info alusel täita Votemo tabelid.

**Comment by LiisKasper** [comment]
Kogu kassettide ja filmide relatsioonide infot Strapis korraga kätte ei saa, tundub, et maht liiga suur ja Strapi saab enne 504 timeout. Sellest ka JSON vead, mida pidasin vääraks dataks. Igatähes baasis midagi ei leidnud ja parandada ei osanud.

Lahendasin teema nii, et kuna soovisid vastavalt festval editionile andemid, siis nüüd nii ongi,( ühe fe mahuga saab Strapi seni hakkama.)
Toimetaja sisestab Festival Editioni (sakk 'VotemoBaseDataFromStrapi' kast A2), mille andemid soovib trida, päring tehakse otse Strapisse, et küsida relatsioone. St koodis on sees token, mida kasutame ka mirrori juures. Seda tuleb selles koodis samuti vahetada, kui token vananeb.
Päringu tegemisel kustutakse tabelid tühjaks ja asendatakse uue infoga. 

Tabel: https://docs.google.com/spreadsheets/d/1o4mQMYNhSXZl6d_0djJW5TJ6JC_PfLYZcCNvO3U7l00/edit#gid=0

**Comment by jaanleppik** [comment]
Vaatan, et on kõik pildid, aga nende originaalid.
Aga siia oleks vaja ainult F_1 ja med_16_9 versiooni. Sest selle edastame otse Votemo süsteemile, kus enam mingit automaatset resize ei toimu. 
Siis peaks testima, et kuidas me selle pildi faili nime alusel assets kataloogi URLi lisamisega pildi terve URLi kokku saame.

**Comment by LiisKasper** [comment]
GrapQl pildi formaate ei tagasta. Saan tagasi ainult esimese kihi info. id, name, alternativeText, caption, width, height, hash. ext, url. Kui sellest infost kuidagi suudad vajaliku urli kokku panna, siis ütle, milline see url olema peaks.

> Siis peaks testima, et kuidas me selle pildi faili nime alusel assets kataloogi URLi lisamisega pildi terve URLi kokku saame.

ei saa aru

**Comment by jaanleppik** [comment]
Eesmärk ol saada selline URL iga filmi / kasseti F1 pildi kohta: 
https://assets.poff.ee/img/F_1_10_Billion_Mouths_17ecb3156b_med_16_9.jpeg

cassettes.et.yaml annab sellise info selle pildi kohta:
                                    ```
                                    id: 13330
                                    name: F_1_10_Billion_Mouths
                                    width: 1920
                                    height: 1080
                                    formats:
                                        _med_16_9:
                                            url: >-
                                                /uploads/F_1_10_Billion_Mouths_17ecb3156b_med_16_9.jpeg
                                            name: F_1_10_Billion_M_med_16_9
                                        thumbnail:
                                            url: >-
                                                /uploads/thumbnail_F_1_10_Billion_Mouths_17ecb3156b.jpeg
                                            name: thumbnail_F_1_10_Billion_Mouths
                                        _small_16_9:
                                            url: >-
                                                /uploads/F_1_10_Billion_Mouths_17ecb3156b_small_16_9.jpeg
                                            name: F_1_10_Billion_M_small_16_9
                                    hash: F_1_10_Billion_Mouths_17ecb3156b
                                    ext: .jpeg
                                    url: >-
                                        /uploads/F_1_10_Billion_Mouths_17ecb3156b.jpeg
```

E siin on hash ja extension ja eri versioonid, aga URLid on miskipärast mitte /assets vaid /uploads kataloogiga.
